FROM python:3.12.5

WORKDIR /backend/

COPY /backend/ .

RUN pip install -r requirements.txt

ENV PORT=8001

CMD ["sh", "-c", "python prepare.py && python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:$PORT"]

